import type {
  ProviderBackendConfig,
  ProviderDefinition,
  ProviderType,
  ProviderTypeInfo,
} from './types';

export const PROVIDER_DEFINITIONS: ProviderDefinition[] = [
  {
    id: 'anthropic',
    name: 'Anthropic',
    icon: '🤖',
    placeholder: 'sk-ant-api03-...',
    model: 'Claude',
    requiresApiKey: true,
    category: 'official',
    envVar: 'ANTHROPIC_API_KEY',
    defaultModelId: 'claude-opus-4-6',
    showModelId: true,
    modelIdPlaceholder: 'claude-opus-4-6',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
  },
  {
    id: 'openai',
    name: 'OpenAI',
    icon: '💚',
    placeholder: 'sk-proj-...',
    model: 'GPT',
    requiresApiKey: true,
    category: 'official',
    envVar: 'OPENAI_API_KEY',
    defaultModelId: 'gpt-5.5',
    isOAuth: true,
    supportsApiKey: true,
    showModelId: true,
    modelIdPlaceholder: 'gpt-5.5',
    supportedAuthModes: ['api_key', 'oauth_browser'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://api.openai.com/v1',
      api: 'openai-responses',
      apiKeyEnv: 'OPENAI_API_KEY',
    },
  },
  {
    id: 'google',
    name: 'Google',
    icon: '🔷',
    placeholder: 'AIza...',
    model: 'Gemini',
    requiresApiKey: true,
    category: 'official',
    envVar: 'GEMINI_API_KEY',
    defaultModelId: 'gemini-3.1-pro-preview',
    showModelId: true,
    modelIdPlaceholder: 'gemini-3.1-pro-preview',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    icon: '🌐',
    placeholder: 'sk-or-v1-...',
    model: 'Multi-Model',
    requiresApiKey: true,
    showModelId: true,
    modelIdPlaceholder: 'anthropic/claude-opus-4.6',
    defaultModelId: 'anthropic/claude-opus-4.6',
    category: 'compatible',
    envVar: 'OPENROUTER_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://openrouter.ai/api/v1',
      api: 'openai-completions',
      apiKeyEnv: 'OPENROUTER_API_KEY',
      headers: {
        'HTTP-Referer': 'https://claw-x.com',
        'X-OpenRouter-Title': 'ClawX',
      },
    },
  },
  {
    id: 'groq',
    name: 'Groq',
    icon: 'G',
    placeholder: 'gsk_...',
    model: 'LPU Inference',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.groq.com/openai/v1',
    showModelId: true,
    modelIdPlaceholder: 'llama-3.3-70b-versatile',
    defaultModelId: 'llama-3.3-70b-versatile',
    category: 'compatible',
    envVar: 'GROQ_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: { baseUrl: 'https://api.groq.com/openai/v1', api: 'openai-completions', apiKeyEnv: 'GROQ_API_KEY' },
  },
  {
    id: 'mistral',
    name: 'Mistral',
    icon: 'M',
    placeholder: 'API key...',
    model: 'Mistral',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.mistral.ai/v1',
    showModelId: true,
    modelIdPlaceholder: 'mistral-large-latest',
    defaultModelId: 'mistral-large-latest',
    category: 'official',
    envVar: 'MISTRAL_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: { baseUrl: 'https://api.mistral.ai/v1', api: 'openai-completions', apiKeyEnv: 'MISTRAL_API_KEY' },
  },
  {
    id: 'xai',
    name: 'xAI',
    icon: 'X',
    placeholder: 'xai-...',
    model: 'Grok',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.x.ai/v1',
    showModelId: true,
    modelIdPlaceholder: 'grok-4',
    defaultModelId: 'grok-4',
    category: 'official',
    envVar: 'XAI_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: { baseUrl: 'https://api.x.ai/v1', api: 'openai-completions', apiKeyEnv: 'XAI_API_KEY' },
  },
  {
    id: 'together',
    name: 'Together AI',
    icon: 'T',
    placeholder: 'API key...',
    model: 'Multi-Model',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.together.xyz/v1',
    showModelId: true,
    modelIdPlaceholder: 'meta-llama/Llama-3.3-70B-Instruct-Turbo',
    defaultModelId: 'meta-llama/Llama-3.3-70B-Instruct-Turbo',
    category: 'compatible',
    envVar: 'TOGETHER_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: { baseUrl: 'https://api.together.xyz/v1', api: 'openai-completions', apiKeyEnv: 'TOGETHER_API_KEY' },
  },
  {
    id: 'deepinfra',
    name: 'DeepInfra',
    icon: 'D',
    placeholder: 'API key...',
    model: 'Multi-Model',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.deepinfra.com/v1/openai',
    showModelId: true,
    modelIdPlaceholder: 'meta-llama/Meta-Llama-3.1-70B-Instruct',
    defaultModelId: 'meta-llama/Meta-Llama-3.1-70B-Instruct',
    category: 'compatible',
    envVar: 'DEEPINFRA_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: { baseUrl: 'https://api.deepinfra.com/v1/openai', api: 'openai-completions', apiKeyEnv: 'DEEPINFRA_API_KEY' },
  },
  {
    id: 'fireworks',
    name: 'Fireworks',
    icon: 'F',
    placeholder: 'fw_...',
    model: 'Multi-Model',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.fireworks.ai/inference/v1',
    showModelId: true,
    modelIdPlaceholder: 'accounts/fireworks/models/llama-v3p1-70b-instruct',
    defaultModelId: 'accounts/fireworks/models/llama-v3p1-70b-instruct',
    category: 'compatible',
    envVar: 'FIREWORKS_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: { baseUrl: 'https://api.fireworks.ai/inference/v1', api: 'openai-completions', apiKeyEnv: 'FIREWORKS_API_KEY' },
  },
  {
    id: 'cerebras',
    name: 'Cerebras',
    icon: 'C',
    placeholder: 'API key...',
    model: 'Cerebras',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.cerebras.ai/v1',
    showModelId: true,
    modelIdPlaceholder: 'llama3.1-70b',
    defaultModelId: 'llama3.1-70b',
    category: 'official',
    envVar: 'CEREBRAS_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: { baseUrl: 'https://api.cerebras.ai/v1', api: 'openai-completions', apiKeyEnv: 'CEREBRAS_API_KEY' },
  },
  {
    id: 'chutes',
    name: 'Chutes',
    icon: 'C',
    placeholder: 'cpk_...',
    model: 'Multi-Model',
    requiresApiKey: true,
    defaultBaseUrl: 'https://llm.chutes.ai/v1',
    showModelId: true,
    modelIdPlaceholder: 'deepseek-ai/DeepSeek-V3-0324',
    defaultModelId: 'deepseek-ai/DeepSeek-V3-0324',
    category: 'compatible',
    envVar: 'CHUTES_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: { baseUrl: 'https://llm.chutes.ai/v1', api: 'openai-completions', apiKeyEnv: 'CHUTES_API_KEY' },
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    icon: 'P',
    placeholder: 'pplx-...',
    model: 'Sonar',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.perplexity.ai',
    showModelId: true,
    modelIdPlaceholder: 'sonar-pro',
    defaultModelId: 'sonar-pro',
    category: 'official',
    envVar: 'PERPLEXITY_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: { baseUrl: 'https://api.perplexity.ai', api: 'openai-completions', apiKeyEnv: 'PERPLEXITY_API_KEY' },
  },
  {
    id: 'venice',
    name: 'Venice AI',
    icon: 'V',
    placeholder: 'API key...',
    model: 'Privacy Models',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.venice.ai/api/v1',
    showModelId: true,
    modelIdPlaceholder: 'llama-3.3-70b',
    defaultModelId: 'llama-3.3-70b',
    category: 'compatible',
    envVar: 'VENICE_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: { baseUrl: 'https://api.venice.ai/api/v1', api: 'openai-completions', apiKeyEnv: 'VENICE_API_KEY' },
  },
  {
    id: 'vercel-ai-gateway',
    name: 'Vercel AI Gateway',
    icon: 'V',
    placeholder: 'vck_...',
    model: 'Multi-Model',
    requiresApiKey: true,
    defaultBaseUrl: 'https://ai-gateway.vercel.sh/v1',
    showModelId: true,
    modelIdPlaceholder: 'openai/gpt-5',
    defaultModelId: 'openai/gpt-5',
    category: 'compatible',
    envVar: 'VERCEL_AI_GATEWAY_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: { baseUrl: 'https://ai-gateway.vercel.sh/v1', api: 'openai-completions', apiKeyEnv: 'VERCEL_AI_GATEWAY_API_KEY' },
  },
  {
    id: 'zai',
    name: 'Z.AI',
    icon: 'Z',
    placeholder: 'API key...',
    model: 'GLM',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.z.ai/api/paas/v4',
    showModelId: true,
    modelIdPlaceholder: 'glm-4.6',
    defaultModelId: 'glm-4.6',
    category: 'official',
    envVar: 'ZAI_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: { baseUrl: 'https://api.z.ai/api/paas/v4', api: 'openai-completions', apiKeyEnv: 'ZAI_API_KEY' },
  },
  {
    id: 'stepfun',
    name: 'StepFun',
    icon: 'S',
    placeholder: 'API key...',
    model: 'Step',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.stepfun.com/v1',
    showModelId: true,
    modelIdPlaceholder: 'step-2-mini',
    defaultModelId: 'step-2-mini',
    category: 'official',
    envVar: 'STEPFUN_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: { baseUrl: 'https://api.stepfun.com/v1', api: 'openai-completions', apiKeyEnv: 'STEPFUN_API_KEY' },
  },
  {
    id: 'qianfan',
    name: 'Qianfan',
    icon: 'Q',
    placeholder: 'API key...',
    model: 'ERNIE',
    requiresApiKey: true,
    defaultBaseUrl: 'https://qianfan.baidubce.com/v2',
    showModelId: true,
    modelIdPlaceholder: 'ernie-4.5-turbo-128k',
    defaultModelId: 'ernie-4.5-turbo-128k',
    category: 'official',
    envVar: 'QIANFAN_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: { baseUrl: 'https://qianfan.baidubce.com/v2', api: 'openai-completions', apiKeyEnv: 'QIANFAN_API_KEY' },
  },
  {
    id: 'qwen',
    name: 'Qwen Cloud',
    icon: 'Q',
    placeholder: 'sk-...',
    model: 'Qwen',
    requiresApiKey: true,
    defaultBaseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    showModelId: true,
    modelIdPlaceholder: 'qwen-max-latest',
    defaultModelId: 'qwen-max-latest',
    category: 'official',
    envVar: 'QWEN_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: { baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1', api: 'openai-completions', apiKeyEnv: 'QWEN_API_KEY' },
  },
  {
    id: 'nvidia',
    name: 'NVIDIA',
    icon: 'N',
    placeholder: 'nvapi-...',
    model: 'NIM',
    requiresApiKey: true,
    defaultBaseUrl: 'https://integrate.api.nvidia.com/v1',
    showModelId: true,
    modelIdPlaceholder: 'meta/llama-3.1-70b-instruct',
    defaultModelId: 'meta/llama-3.1-70b-instruct',
    category: 'compatible',
    envVar: 'NVIDIA_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: { baseUrl: 'https://integrate.api.nvidia.com/v1', api: 'openai-completions', apiKeyEnv: 'NVIDIA_API_KEY' },
  },
  {
    id: 'huggingface',
    name: 'Hugging Face',
    icon: 'H',
    placeholder: 'hf_...',
    model: 'Inference',
    requiresApiKey: true,
    defaultBaseUrl: 'https://router.huggingface.co/v1',
    showModelId: true,
    modelIdPlaceholder: 'meta-llama/Llama-3.1-70B-Instruct',
    defaultModelId: 'meta-llama/Llama-3.1-70B-Instruct',
    category: 'compatible',
    envVar: 'HUGGINGFACE_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: { baseUrl: 'https://router.huggingface.co/v1', api: 'openai-completions', apiKeyEnv: 'HUGGINGFACE_API_KEY' },
  },
  {
    id: 'litellm',
    name: 'LiteLLM',
    icon: 'L',
    placeholder: 'API key...',
    model: 'Gateway',
    requiresApiKey: true,
    defaultBaseUrl: 'http://localhost:4000/v1',
    showBaseUrl: true,
    showModelId: true,
    modelIdPlaceholder: 'openai/gpt-5',
    defaultModelId: 'openai/gpt-5',
    category: 'compatible',
    envVar: 'LITELLM_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: { baseUrl: 'http://localhost:4000/v1', api: 'openai-completions', apiKeyEnv: 'LITELLM_API_KEY' },
  },
  {
    id: 'lmstudio',
    name: 'LM Studio',
    icon: 'L',
    placeholder: 'Not required',
    model: 'Local',
    requiresApiKey: false,
    defaultBaseUrl: 'http://localhost:1234/v1',
    showBaseUrl: true,
    showModelId: true,
    modelIdPlaceholder: 'local-model',
    defaultModelId: 'local-model',
    category: 'local',
    supportedAuthModes: ['local'],
    defaultAuthMode: 'local',
    supportsMultipleAccounts: true,
    providerConfig: { baseUrl: 'http://localhost:1234/v1', api: 'openai-completions', apiKeyEnv: 'LMSTUDIO_API_KEY' },
  },
  {
    id: 'vllm',
    name: 'vLLM',
    icon: 'V',
    placeholder: 'Not required',
    model: 'Local',
    requiresApiKey: false,
    defaultBaseUrl: 'http://localhost:8000/v1',
    showBaseUrl: true,
    showModelId: true,
    modelIdPlaceholder: 'served-model-name',
    defaultModelId: 'served-model-name',
    category: 'local',
    supportedAuthModes: ['local'],
    defaultAuthMode: 'local',
    supportsMultipleAccounts: true,
    providerConfig: { baseUrl: 'http://localhost:8000/v1', api: 'openai-completions', apiKeyEnv: 'VLLM_API_KEY' },
  },
  {
    id: 'sglang',
    name: 'SGLang',
    icon: 'S',
    placeholder: 'Not required',
    model: 'Local',
    requiresApiKey: false,
    defaultBaseUrl: 'http://localhost:30000/v1',
    showBaseUrl: true,
    showModelId: true,
    modelIdPlaceholder: 'served-model-name',
    defaultModelId: 'served-model-name',
    category: 'local',
    supportedAuthModes: ['local'],
    defaultAuthMode: 'local',
    supportsMultipleAccounts: true,
    providerConfig: { baseUrl: 'http://localhost:30000/v1', api: 'openai-completions', apiKeyEnv: 'SGLANG_API_KEY' },
  },
  {
    id: 'cloudflare-ai-gateway',
    name: 'Cloudflare AI Gateway',
    icon: 'C',
    placeholder: 'API key...',
    model: 'Gateway',
    requiresApiKey: true,
    defaultBaseUrl: 'https://gateway.ai.cloudflare.com/v1/{account_id}/{gateway_id}/openai',
    showBaseUrl: true,
    showModelId: true,
    modelIdPlaceholder: 'openai/gpt-5',
    defaultModelId: 'openai/gpt-5',
    category: 'compatible',
    envVar: 'CLOUDFLARE_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: { baseUrl: 'https://gateway.ai.cloudflare.com/v1/{account_id}/{gateway_id}/openai', api: 'openai-completions', apiKeyEnv: 'CLOUDFLARE_API_KEY' },
  },
  {
    id: 'ark',
    name: 'ByteDance Ark',
    icon: 'A',
    placeholder: 'your-ark-api-key',
    model: 'Doubao',
    requiresApiKey: true,
    defaultBaseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    showBaseUrl: true,
    showModelId: true,
    modelIdPlaceholder: 'ep-20260228000000-xxxxx',
    category: 'official',
    envVar: 'ARK_API_KEY',
    codePlanPresetBaseUrl: 'https://ark.cn-beijing.volces.com/api/coding/v3',
    codePlanPresetModelId: 'ark-code-latest',
    codePlanDocsUrl: 'https://www.volcengine.com/docs/82379/1928261?lang=zh',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
      api: 'openai-completions',
      apiKeyEnv: 'ARK_API_KEY',
    },
  },
  {
    id: 'moonshot',
    name: 'Moonshot (CN)',
    icon: '🌙',
    placeholder: 'sk-...',
    model: 'Kimi',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.moonshot.cn/v1',
    defaultModelId: 'kimi-k2.6',
    showModelId: true,
    modelIdPlaceholder: 'kimi-k2.6',
    category: 'official',
    envVar: 'MOONSHOT_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://api.moonshot.cn/v1',
      api: 'openai-completions',
      apiKeyEnv: 'MOONSHOT_API_KEY',
      models: [
        {
          id: 'kimi-k2.6',
          name: 'Kimi K2.6',
          reasoning: false,
          input: ['text'],
          cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
          contextWindow: 256000,
          maxTokens: 8192,
        },
      ],
    },
  },
  {
    id: 'moonshot-global',
    name: 'Moonshot (Global)',
    icon: '🌙',
    placeholder: 'sk-...',
    model: 'Kimi',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.moonshot.ai/v1',
    defaultModelId: 'kimi-k2.6',
    showModelId: true,
    modelIdPlaceholder: 'kimi-k2.6',
    category: 'official',
    envVar: 'MOONSHOT_GLOBAL_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://api.moonshot.ai/v1',
      api: 'openai-completions',
      apiKeyEnv: 'MOONSHOT_GLOBAL_API_KEY',
      models: [
        {
          id: 'kimi-k2.6',
          name: 'Kimi K2.6',
          reasoning: false,
          input: ['text'],
          cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
          contextWindow: 256000,
          maxTokens: 8192,
        },
      ],
    },
  },
  {
    id: 'siliconflow',
    name: 'SiliconFlow (CN)',
    icon: '🌊',
    placeholder: 'sk-...',
    model: 'Multi-Model',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.siliconflow.cn/v1',
    showModelId: true,
    modelIdPlaceholder: 'deepseek-ai/DeepSeek-V3',
    defaultModelId: 'deepseek-ai/DeepSeek-V3',
    category: 'compatible',
    envVar: 'SILICONFLOW_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://api.siliconflow.cn/v1',
      api: 'openai-completions',
      apiKeyEnv: 'SILICONFLOW_API_KEY',
    },
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    icon: '🐋',
    placeholder: 'sk-...',
    model: 'DeepSeek',
    requiresApiKey: true,
    defaultBaseUrl: 'https://api.deepseek.com/v1',
    showModelId: true,
    modelIdPlaceholder: 'deepseek-v4-pro',
    defaultModelId: 'deepseek-v4-pro',
    apiKeyUrl: 'https://platform.deepseek.com/api_keys',
    category: 'official',
    envVar: 'DEEPSEEK_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://api.deepseek.com/v1',
      api: 'openai-completions',
      apiKeyEnv: 'DEEPSEEK_API_KEY',
    },
  },
  {
    id: 'minimax-portal',
    name: 'MiniMax (Global)',
    icon: '☁️',
    placeholder: 'sk-...',
    model: 'MiniMax',
    requiresApiKey: false,
    isOAuth: true,
    supportsApiKey: true,
    defaultModelId: 'MiniMax-M2.7',
    showModelId: true,
    modelIdPlaceholder: 'MiniMax-M2.7',
    apiKeyUrl: 'https://platform.minimax.io',
    category: 'official',
    envVar: 'MINIMAX_API_KEY',
    supportedAuthModes: ['oauth_device', 'api_key'],
    defaultAuthMode: 'oauth_device',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://api.minimax.io/anthropic',
      api: 'anthropic-messages',
      apiKeyEnv: 'MINIMAX_API_KEY',
      models: [
        {
          id: 'MiniMax-M2.7',
          name: 'MiniMax M2.7',
          reasoning: false,
          input: ['text'],
          cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
          contextWindow: 204800,
          maxTokens: 131072,
        },
      ],
    },
  },
  {
    id: 'minimax-portal-cn',
    name: 'MiniMax (CN)',
    icon: '☁️',
    placeholder: 'sk-...',
    model: 'MiniMax',
    requiresApiKey: false,
    isOAuth: true,
    supportsApiKey: true,
    defaultModelId: 'MiniMax-M2.7',
    showModelId: true,
    modelIdPlaceholder: 'MiniMax-M2.7',
    apiKeyUrl: 'https://platform.minimaxi.com/',
    category: 'official',
    envVar: 'MINIMAX_CN_API_KEY',
    supportedAuthModes: ['oauth_device', 'api_key'],
    defaultAuthMode: 'oauth_device',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://api.minimaxi.com/anthropic',
      api: 'anthropic-messages',
      apiKeyEnv: 'MINIMAX_CN_API_KEY',
      models: [
        {
          id: 'MiniMax-M2.7',
          name: 'MiniMax M2.7',
          reasoning: false,
          input: ['text'],
          cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
          contextWindow: 204800,
          maxTokens: 131072,
        },
      ],
    },
  },
  {
    id: 'modelstudio',
    name: 'Model Studio',
    icon: '☁️',
    placeholder: 'sk-...',
    model: 'Qwen',
    requiresApiKey: true,
    defaultBaseUrl: 'https://coding.dashscope.aliyuncs.com/v1',
    showBaseUrl: true,
    defaultModelId: 'qwen3.6-plus',
    showModelId: true,
    showModelIdInDevModeOnly: true,
    modelIdPlaceholder: 'qwen3.6-plus',
    category: 'official',
    envVar: 'MODELSTUDIO_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
    providerConfig: {
      baseUrl: 'https://coding.dashscope.aliyuncs.com/v1',
      api: 'openai-completions',
      apiKeyEnv: 'MODELSTUDIO_API_KEY',
    },
  },
  {
    id: 'ollama',
    name: 'Ollama',
    icon: '🦙',
    placeholder: 'Not required',
    requiresApiKey: false,
    defaultBaseUrl: 'http://localhost:11434/v1',
    showBaseUrl: true,
    showModelId: true,
    modelIdPlaceholder: 'qwen3:latest',
    category: 'local',
    supportedAuthModes: ['local'],
    defaultAuthMode: 'local',
    supportsMultipleAccounts: true,
  },
  {
    id: 'custom',
    name: 'Custom',
    icon: '⚙️',
    placeholder: 'API key...',
    requiresApiKey: true,
    showBaseUrl: true,
    showModelId: true,
    modelIdPlaceholder: 'your-provider/model-id',
    category: 'custom',
    envVar: 'CUSTOM_API_KEY',
    supportedAuthModes: ['api_key'],
    defaultAuthMode: 'api_key',
    supportsMultipleAccounts: true,
  },
];

const PROVIDER_DEFINITION_MAP = new Map(
  PROVIDER_DEFINITIONS.map((definition) => [definition.id, definition]),
);

export function getProviderDefinition(
  type: ProviderType | string,
): ProviderDefinition | undefined {
  return PROVIDER_DEFINITION_MAP.get(type as ProviderType);
}

export function getProviderTypeInfo(
  type: ProviderType,
): ProviderTypeInfo | undefined {
  return getProviderDefinition(type);
}

export function getProviderEnvVar(type: string): string | undefined {
  return getProviderDefinition(type)?.envVar;
}

export function getProviderDefaultModel(type: string): string | undefined {
  return getProviderDefinition(type)?.defaultModelId;
}

export function getProviderBackendConfig(
  type: string,
): ProviderBackendConfig | undefined {
  return getProviderDefinition(type)?.providerConfig;
}

export function getProviderUiInfoList(): ProviderTypeInfo[] {
  return PROVIDER_DEFINITIONS;
}

export function getKeyableProviderTypes(): string[] {
  return PROVIDER_DEFINITIONS.filter((definition) => definition.envVar).map(
    (definition) => definition.id,
  );
}
